### ISSUE TITLE
Serverless: Migrations - DATABASE_URL environment variable required

### ISSUE THREAD

**Issue by sethigoldy-zz** [Nevon/serverless-pg-migrations#4]
HI

I have successfully deployed the lambda function for my app but whenever I try to run the command `sls migrate up` it outputs the following error:

> Serverless: Migrations - DATABASE_URL environment variable required

I have added `up` and `down` function in serverless.yml

````
up:
    handler: migrations.up
    timeout: 30
    environment:
      DATABASE_URL: postgres://{user}:{pass}@{rds_url}:5432/{db_name}
  down:
    handler: migrations.down
    timeout: 30
    environment:
      DATABASE_URL: postgres://{user}:{pass}@{rds_url}:5432/{db_name}
````

Please let me know what I have miss/there's an issue and will it support Postgres version 10 or above.
